AWSTemplateFormatVersion: 2010-09-09
Description: {}
Metadata: {} 
Parameters:
vpccidr:
  Description: provide the cidr
  Type: String
pubsub4AZ:
  Description: provide availability zone
  Type: String
pubsub4cidr:
  Description: provide cidr for public subnet
  Type: String
prisub4cidr:
  Description: provide the vpcid
  Type: String
prisubcidrId:
  Description: provide the cidr
  Type: String
Mappings: {} 
Conditions: {} 
Resources: 
vpc4:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: !Ref vpccidr
    Tags:
      - Key: Name
        Value: vpc4
pubsub4:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: !Ref pubsub4AZ
    VpcId: !Ref vpc4
    CidrBlock: !Ref pubsub4cidr
    Tags:
      - Key: Name
        Value: pubsub4
prisub4:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: !Ref prisubaz
    VpcId: !Ref vpc4
    CidrBlock: !Ref privsub4az
    Tags:
      - Key: Name
        Value: prisub4
        Outputs: {}